### ISSUE TITLE
login option no longer available on website

### ISSUE THREAD

**Issue by arkypita** [Microsoft/Code-Hunt#1]
I am a software developer and I am using https://www.codehunt.com/ to teach programming basics to third part people.

Since a couple of day the option for login with any account (ms, google etc) does not appears anymore, so we cannot continue from last scored level but only restart from first level.
I have already checked different browsers, computer, cleaning cookies etc...
Any idea?

**Comment by pelikhan** [comment]
Sorry for the inconvience. As part of compliance work for GDPR, we have removed the ability to store an account.
